debug: false # ??? ??? ???? ???
management:
  endpoints:
    web:
      exposure:
        include: "*"  # ?????? ?????? ?? ??? '*'

logging:
  level:
    me.eatnows.lectureboard: debug  # me.eatnows.lectureboard ??? ??? ???? Debug? ???
    org.springframework.web.servlet: debug # reqyest, response ??? debug? ?? ?? ?? ??? debug? false? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA? ??? ? ?? ??? ??? ??? ??? ? ?? (??? ????? ??? ? ??)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lecture_board
    username: chodong
    password: eatnows!#1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # ???? ??? ?? ? ?? ?????? ??? SQL? ??? ? ?? resource/data.sql ??? ???? ??
    hibernate.ddl-auto: create # ???? ???? ??? ?? ??
    open-in-view: false
    show-sql: true # SQL? ? ? ???
    properties:
      hibernate.format_sql: true # SQL? ????? ??
      hibernate.default_batch_fetch_size: 100 # JPA?? ??? ??? ??? ? ? ?? ??? ???? ? ? ?? ?
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  sql.init.mode: always # resource/data.sql ? ?? ??? ???? ?? ?

#---

#spring:
#  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none

